// This file has been generated by Specta. DO NOT EDIT.

import { createTauRPCProxy as createProxy, type InferCommandOutput } from 'taurpc'
type TAURI_CHANNEL<T> = (response: T) => void


export type HelloParams = { name: string }

export type HelloResponse = { message: string }

const ARGS_MAP = { '':'{"hello":["params"],"hello_world":[]}' }
export type Router = { "": {hello: (params: HelloParams) => Promise<HelloResponse>, 
hello_world: () => Promise<void>} };


export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
export type { InferCommandOutput }
